"""initial_database_schema

Revision ID: a68d4197aae1
Revises: 
Create Date: 2025-11-07 04:09:35.037880
-------------
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68d4197aae1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('simple', 'measurable', name='habittype'), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date', 'habit_entries', ['date'], unique=False)
    op.create_index('idx_habitId_completed', 'habit_entries', ['habit_id', 'is_completed'], unique=False)
    op.create_index('idx_habitId_date', 'habit_entries', ['habit_id', 'date'], unique=False)
    op.create_index('idx_isCompleted', 'habit_entries', ['is_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_isCompleted', table_name='habit_entries')
    op.drop_index('idx_habitId_date', table_name='habit_entries')
    op.drop_index('idx_habitId_completed', table_name='habit_entries')
    op.drop_index('idx_date', table_name='habit_entries')
    op.drop_table('habit_entries')
    op.drop_table('habits')
    # ### end Alembic commands ###
